### ISSUE TITLE
Ishlatish to'g'risida yo'riqnoma

### ISSUE THREAD

**Issue by shakhrillodev** [u2b3k/uz-hunspell#2]
Assalomu alaykum ushbu fayllardan biror dasturlash tilida foydalanish to'g'risida ko'rsatma bera olasizmi? Js bo'lsa yaxshi bo'lardi. O'zim izlandim biroq ishlatish yo'lini topolmadim.

**Comment by u2b3k** [comment]
> O'zim izlandim biroq ishlatish yo'lini topolmadim.

Vaalaykum assalom. O'zingiz ishlaydigan muhitga Hunspell ning binding lari yoki kutubxonasini qo'shib, o'sha orqali ishlatasiz. 
Masalan: https://www.npmjs.com/package/nodehun-native

**Comment by shakhrillodev** [comment]
Assallomu alaykum. Yo'l yo'riq uchun rahmat. Men ushbu: https://www.npmjs.com/package/nodehun muhit orqali proyektingizni ishlatishga muvaffaq bo'ldim. Katta rahmat. Bu proyektni ishlatish uchun visual studio installerdan workloadslar orasidan destkop development with c++ ni o'rnatish zarur ekan.
